services:
  crypto-assistant:
    build: .
    container_name: crypto-assistant
    restart: unless-stopped

    env_file:
      - .env

    volumes:
      - ./data:/app/data

    environment:
      - TZ=Europe/Paris
